import test from 'node:test';
import assert from 'node:assert/strict';
import {TONES,AMPS,DEFAULT_RIG} from '../dist/data.js';
import {adaptTone,validateTone,validateRig,validateBackup,validateResearch,validateGrounding,backupParts} from '../dist/core.js';
const rig=()=>validateRig(structuredClone(DEFAULT_RIG));
const savedTone=()=>({id:'one',tone:TONES[0],rig:rig(),values:{...TONES[0].base},guitarTone:8,created:'2026-09-14',note:''});
test('all library recipes adapt to every supported amplifier without invalid or missing knobs',()=>{for(const tone of TONES){validateTone(tone);for(const amp of AMPS){const before=JSON.stringify(tone);const result=adaptTone(tone,{...rig(),amp:validateRig({...rig(),amp}).amp});assert(result.controls.every(k=>amp.controls.includes(k)));assert(Object.values(result.values).every(v=>Number.isFinite(v)&&v>=0&&v<=10));assert.equal(JSON.stringify(tone),before)}}});
test('Crush clean channel has no actionable gain, and a missing drive pedal uses dirty gain',()=>{const r={...rig(),amp:AMPS.find(a=>a.id==='orange-crush-35rt')};assert(!adaptTone(TONES[0],r).controls.includes('gain'));const driven=adaptTone(TONES.find(t=>t.id==='teen-spirit'),r);assert(driven.controls.includes('gain'));assert.equal(driven.channel,'DIRTY');assert(driven.notes.some(n=>n.includes('rough substitute')))});
test('Katana and Mustang omit physical presence; Mustang middle retains edit-menu note',()=>{for(const id of ['boss-katana-50-gen3','fender-mustang-lt25']){const a=AMPS.find(a=>a.id===id);const result=adaptTone(TONES[0],{...rig(),amp:a});assert(!result.controls.includes('presence'));if(id.includes('mustang'))assert(result.notes.some(n=>n.includes('edit menu')))}});
test('pickup correction responds to output mismatch, missing effects are explicit',()=>{const tone=TONES.find(t=>t.id==='little-wing'),r=rig();const single=adaptTone(tone,r),hot=adaptTone(tone,{...r,pickup:'humbucker'});assert(hot.values.gain<single.values.gain);assert(hot.values.treble>single.values.treble);const chorus=adaptTone(TONES[0],r);assert(chorus.effects.find(e=>e.type==='chorus').available===false)});
test('backup validates atomically and rejects duplicate IDs, NaN, unknown pickup and hostile source links',()=>{const b={format:'tonezero-backup',version:1,rig:rig(),saved:[savedTone()]};assert.equal(validateBackup(b).saved.length,1);assert.throws(()=>validateBackup({...b,saved:[savedTone(),savedTone()]}),/duplicate/);assert.throws(()=>validateBackup({...b,rig:{...rig(),pickup:'mystery'}}));const bad=savedTone();bad.values.gain=NaN;assert.throws(()=>validateBackup({...b,saved:[bad]}));const t=validateTone({...TONES[0],sources:[{title:'bad',url:'javascript:alert(1)'}]});assert.equal(t.sources.length,0)});
test('large exports split into independently importable parts without losing tones or research',()=>{const entries=Array.from({length:30},(_,i)=>({...savedTone(),id:'item-'+i,tone:{...TONES[0],research:{rawText:'Original researched content. '.repeat(250),searchEntryPoint:'<div>Google Search suggestions</div>',sources:[{title:'Source',url:'https://example.com'}]}}}));const parts=backupParts(rig(),entries,50000);assert(parts.length>1);const restored=parts.flatMap(part=>{assert(Buffer.byteLength(part)<=50000);return validateBackup(JSON.parse(part)).saved});assert.equal(restored.length,entries.length);assert(restored[0].tone.research.rawText.startsWith('Original'));assert.equal(new Set(restored.map(s=>s.id)).size,entries.length)});
test('AI gear validation rejects invented capability enums and clamps unsafe data at boundaries',()=>{assert.throws(()=>validateResearch({summary:'Found',profile:{name:'Fake',pickup:'laser'}},'guitar'));assert.throws(()=>validateResearch({summary:'Found',profile:{name:'Fake',controls:['master-volume']}},'amp'));assert.throws(()=>validateResearch({found:false,summary:'Please specify the model year.'},'guitar'),/model year/);const p=validateResearch({summary:'Found',profile:{name:'Guitar',pickup:'single',specs:[{label:'Body',value:'Alder'}]}},'guitar');assert.equal(p.profile.pickup,'single')});
test('research attribution validates provider and keeps legacy Google suggestions separate from Tavily',()=>{const legacy={rawText:'Research',searchEntryPoint:'<div>Google Search suggestions</div>',sources:[]};assert.equal(validateGrounding(legacy).searchProvider,'google');assert.equal(validateGrounding(legacy).searchEntryPoint,legacy.searchEntryPoint);assert.equal(validateGrounding({...legacy,searchProvider:'tavily'}).searchEntryPoint,'');for(const searchProvider of ['unknown','',null,{},42])assert.throws(()=>validateGrounding({...legacy,searchProvider}),/provider/)});
test('research provider and source excerpts survive backups for every gear type and saved song',()=>{
  for(const searchProvider of ['tavily','google']){
    const research={searchProvider,rawText:'Original research',searchEntryPoint:searchProvider==='google'?'<div>Google Search suggestions</div>':'',sources:[{title:'Manufacturer',url:'https://example.com/specs',supports:'An excerpt from the source.'}],supports:[{text:'An excerpt from the source.',sourceIndices:[0]}]};
    const researchedRig={...rig(),guitarResearch:research,amp:{...rig().amp,research},pedals:[{name:'Example pedal',type:'overdrive',research}]};
    const tone={...savedTone(),tone:{...TONES[0],research},rig:researchedRig};
    const restored=validateBackup(JSON.parse(backupParts(researchedRig,[tone])[0]));
    for(const value of [restored.rig.guitarResearch,restored.rig.amp.research,restored.rig.pedals[0].research,restored.saved[0].tone.research,restored.saved[0].rig.guitarResearch,restored.saved[0].rig.amp.research,restored.saved[0].rig.pedals[0].research])assert.deepEqual(value,research);
  }
});
